version: '3'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      # You can pass environment variables here or use a .env file
      - GOOGLE_APPLICATION_CREDENTIALS='config\\Key.json'
      - GEMINI_API_KEY=AIzaSyDLFxz-0N5fAm7EoL17UispDkPf15TGNEE
      - SECRET_KEY=your_secret_key
    volumes:
      - ./server:/app  # Optional: mount your server code for live development

  client:
    build: ./client
    ports:
      - "3000:80"  # Maps container's port 80 to host port 3000 for the React app
    volumes:
      - ./client:/app  # Optional: mount your client code for live development

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    restart: always
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: LocalKafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
